power_data <- read.csv(file = "household_power_consumption.txt", stringsAsFactors=FALSE, sep = ";", dec = ".", header = T)
power_data$Date <- as.Date(power_data$Date, format = "%d/%m/%Y")
power_data_plot <- power_data[(power_data$Date == "2007-02-01") | (power_data$Date == "2007-02-02"),]
DateTime <- as.POSIXct(paste(power_data_plot$Date, power_data_plot$Time, sep=" "))
Sub_metering_1 <- as.numeric(power_data_plot$Sub_metering_1)
Sub_metering_2 <- as.numeric(power_data_plot$Sub_metering_2)
Sub_metering_3 <- as.numeric(power_data_plot$Sub_metering_3)
Voltage <- as.numeric(power_data_plot$Voltage)
Global_reactive_power <- as.numeric(power_data_plot$Global_reactive_power)
power_data_plot$Global_active_power <- as.numeric(as.character(power_data_plot$Global_active_power))
png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(DateTime, power_data_plot$Global_active_power, type="l", xlab= "", ylab = "Global Active Power (kilowatts)")
plot(DateTime, Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(DateTime, Sub_metering_1, type="l", xlab= "", ylab = "Energy sub metering")
lines(DateTime, Sub_metering_2, type = "l", col = "red", lty=2, lwd=2)
lines(DateTime, Sub_metering_3, type = "l", col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col = c("black", "red", "blue"))
plot(DateTime, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()